# Generated by Django 3.0.8 on 2020-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('country', models.CharField(default='', max_length=20)),
                ('won', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('coach', models.CharField(default='', max_length=1000)),
                ('executive', models.CharField(default='', max_length=1000)),
                ('captain', models.CharField(default='', max_length=1000)),
                ('flag', models.CharField(default='', max_length=1000)),
                ('players', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
