# Generated by Django 3.0.8 on 2020-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='executive',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
