# Generated by Django 3.0.8 on 2020-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('team', models.IntegerField()),
                ('country', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('debut', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=50)),
                ('shoot', models.CharField(max_length=50)),
                ('matches', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('loggedTime', models.DateTimeField(auto_now_add=True)),
                ('loggedDuration', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
