# Generated by Django 3.0.8 on 2020-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
